### ISSUE TITLE
Problems building bert with squad config

### ISSUE THREAD

**Issue by Skemba** [deepmipt/DeepPavlov#1084]
Hi,

When I try to build bert with squad config with

`model = build_model(configs.squad.squad, download=True)`

i get the following error:

> File "/deeppavlov/core/layers/tf_layers.py", line 26, in module INITIALIZER = tf.orthogonal_initializer AttributeError: module 'tensorflow' has no attribute 'orthogonal_initializer'

I'm using tensorflow-gpu 2.0.0, on ubuntu 18.04.

Any idea how to solve this?

P.S. I ran this code before and it worked, stopped working recently, not sure exactly when

**Comment by yoptar** [comment]
Hi @Skemba,
We did not update our models to work on TF2.0 yet, but everything should work on `tensorflow-gpu==1.14.0`

**Comment by Rmsharks4** [comment]
What is the TF Version for Non-GPUs? Also as a suggestion while your shifting to TF2.0, you can update your requirements.txt so that older packages may get automatically downgraded.
